language: c++
dist: trusty
sudo: required
services:
    - docker
install:
    - docker build -t openskystacker .
script:
    - docker run -it openskystacker /bin/sh -c 'qmake -qt=qt5 && make'
after-script:
    - docker run -it openskystacker /bin/sh -c 'qmake -qt=qt5 CONFIG+=test && make && bin/testoss'