matrix:
    include:
      - os: linux
        language: c++
        services:
          - docker
      - os: osx
        osx_image: xcode9
install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install qt opencv libraw ccfits; else docker build -t openskystacker .; fi
script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then qmake && make; else docker run -it openskystacker /bin/sh -c 'qmake -qt=qt5 && make'; fi
after_script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then qmake CONFIG+=test && make; else docker run -it openskystacker /bin/sh -c 'qmake -qt=qt5 CONFIG+=test && make && bin/testoss'; fi