language: c++
services:
  - docker
install:
  - docker pull benjuan26/openskystacker
script:
  - >
    docker run -e COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN -e TRAVIS_BRANCH=$TRAVIS_BRANCH -v $PWD:/OpenSkyStacker -it benjuan26/openskystacker /bin/sh -c '
    qmake -qt=qt5 CONFIG+=coverage &&
    make && make install && ldconfig &&
    bin/oss-test -d ../samples &&
    coveralls -b libstacker -i libstacker > /dev/null'
