language: c++
dist: trusty
before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt5-default libopencv-dev libraw-dev
script:
    - qmake -qt=qt5 -v
    - qmake -qt=qt5
    - make
