name: openskystacker # you probably want to 'snapcraft register <name>'
version: '0.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Open-source, multi-platform astroimaging stacker # 79 char long summary
description: |
  OpenSkyStacker
icon: openskystacker-logoabbr-512.png

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  openskystacker:
    command: qt5-launch bin/OpenSkyStacker
    plugs:
      - unity7
      - home

parts:
  openskystacker:
    # See 'snapcraft plugins'
    plugin: qmake
    source: .
    qt-version: qt5
    options:
     - "CONFIG+=snapcraft"
    build-packages:
      - qtdeclarative5-dev-tools
      - qt5-default
      - qtbase5-dev
      - qtdeclarative5-dev
    stage-packages:
      - libqt5gui5
    after: [qt5conf]
